name: HA Promtail
slug: ha_promtail
description: Promtail for HAOS with journald scraping
url: https://github.com/Muriel2Horak/ha-promtail
version: 0.1.5
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
startup: services
boot: auto
init: false
host_network: false
host_pid: true
privileged:
  - SYS_ADMIN
  - SYSLOG
  - DAC_READ_SEARCH
  - SYS_PTRACE
  - SYS_CHROOT
  - SYS_RESOURCE
  - SYS_TIME
  - SYS_NICE
full_access: true
journald: true
map:
  - share
  - ssl
options:
  client:
    url: http://10.0.0.160:3100/loki/api/v1/push
    username: ""
    password: ""
    cafile: ""
    certfile: ""
    keyfile: ""
    servername: ""
  log_level: info
schema:
  client:
    url: str
    username: str?
    password: password?
    cafile: str?
    certfile: str?
    keyfile: str?
    servername: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  9080/tcp: null
ports_description:
  9080/tcp: Promtail web server
watchdog: http://[HOST]:[PORT:9080]/ready
stage: stable
